apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus-stack
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: packages.glasskube.dev/v1alpha1
kind: ClusterPackage
metadata:
  name: kube-prometheus-stack
spec:
  packageInfo:
    name: kube-prometheus-stack
    repositoryName: glasskube
    version: v62.7.0+1
  values:
    alertmanagerEnabled:
      value: "false"
    grafanaDomain:
      value: ""
    grafanaEnabled:
      value: "true"
    prometheusNodeExporterHostNetwork:
      value: "true"
    prometheusRetention:
      value: 30d
    prometheusStorageSize:
      value: 10Gi
